import {
  Server,
  Database,
  Cloud,
  Monitor,
  Cpu,
  MemoryStick,
  HardDriveIcon,
  Globe,
  Router,
  Network,
  Download,
  Upload,
  FileText,
  Music,
  Video,
  Image,
  Archive,
  Folder,
  Zap,
  Shield,
  type LucideIcon
} from "lucide-react";
import { QBittorrentIcon } from "./QBittorrentIcon";

// Available icons for agents
export const availableIcons: { name: string; icon: LucideIcon | React.ComponentType<React.SVGProps<SVGSVGElement>> }[] = [
  { name: "Server", icon: Server },
  { name: "Database", icon: Database },
  { name: "Cloud", icon: Cloud },
  { name: "Monitor", icon: Monitor },
  { name: "Cpu", icon: Cpu },
  { name: "MemoryStick", icon: MemoryStick },
  { name: "HardDrive", icon: HardDriveIcon },
  { name: "Globe", icon: Globe },
  { name: "Router", icon: Router },
  { name: "Network", icon: Network },
  { name: "Download", icon: Download },
  { name: "Upload", icon: Upload },
  { name: "FileText", icon: FileText },
  { name: "Music", icon: Music },
  { name: "Video", icon: Video },
  { name: "Image", icon: Image },
  { name: "Archive", icon: Archive },
  { name: "Folder", icon: Folder },
  { name: "Zap", icon: Zap },
  { name: "Shield", icon: Shield },
  { name: "QBittorrent", icon: QBittorrentIcon },
];
